project:
  type: website

website:
  title: "Confirm"
  site-url: https://confirmlabs.org
  navbar:
    title: false
    background: white
    pinned: false
    left:
      - href: index.qmd
        text: Confirm

format:
  html:
    css: styles.css
    toc: true
    toc-location: left
    theme: cosmo

filters:
   - lightbox
lightbox: auto

execute:
  freeze: auto

resources:
  - CNAME 