project:
  type: website

website:
  title: "Confirm"
  site-url: https://confirmlabs.org
  navbar:
    title: false
    background: white
    pinned: false
    left:
      - href: index.qmd
        text: Confirm

citation: true
link-citations: true
csl: ieee.csl

google-scholar: true

format:
  html:
    css: styles.css
    toc: true
    toc-location: left
    theme: cosmo
    grid:
      margin-width: 350px

filters:
   - lightbox
lightbox: auto

execute:
  freeze: auto

resources:
  - CNAME 