project:
  type: website

website:
  title: "Confirm"
  navbar:
    title: false
    background: white
    pinned: false
    left:
      - href: index.qmd
        text: Confirm

format:
  html:
    css: styles.css
    toc: true
    toc-location: left
    code-fold: true

filters:
   - lightbox
lightbox: auto

execute:
  freeze: false

resources:
  - CNAME 